import { type TEvent, TEventType } from "./types.js";

export const events: TEvent[] = [
    {
        name: "Lorencia Online Lottery",
        times: Array.from(Array(24).keys()).map((number) => `${number.toString().padStart(2, "0")}:55`),
        type: TEventType.CASUAL,
        map: "Lorencia",
        rewards: ["150 WCoin"],
    },
    {
        name: "Atlans Lost Treasures",
        times: ["01:10", "07:10", "13:10", "19:10"],
        type: TEventType.CASUAL,
        map: "Atlans",
        rewards: [
            "Talisman of Luck",
            "Box of Kundun +1",
            "Box of Kundun +2",
            "Box of Kundun +3",
            "Box of Kundun +4",
            "Box of Kundun +5",
            "Jewel of Bless",
            "Jewel of Soul",
            "Jewel of Life",
            "Jewel of Creation",
            "Gemstone",
            "Jewel of Guardian",
        ],
    },
    {
        name: "Red Dragon Invasion",
        times: ["00:45", "03:45", "06:45", "09:45", "12:45", "15:45", "18:45", "21:45"],
        type: TEventType.CASUAL,
        map: "Lorencia",
        rewards: ["Excellent Item with 1-4 excellent options"],
    },
    {
        name: "White Wizard",
        times: ["00:50", "04:50", "08:50", "12:50", "16:50", "20:50"],
        type: TEventType.CASUAL,
        map: "Lorencia / Noria / Devias",
        rewards: ["Wizard's Ring", "5 Jewel of Creation"],
    },
    {
        name: "Boss Battle",
        times: ["01:30", "03:30", "05:30", "07:30", "11:30", "13:30", "15:30", "17:30", "19:30", "21:30", "23:30"],
        type: TEventType.IMPORTANT,
        map: "Loren Market",
        rewards: [
            "Fire Kentaur ~ 10 Talisman of Luck",
            "Devil Sorcerer ~ 2 Talisman of Chaos Assembly",
            "Night Elf Mage ~ 5 Excellent Mastery Equipment (all mastery sets)",
            "Pharaoh ~ 5 piece: Sealed Silver Box / Silver Key / Sealed Golden Box / Golden Key",
            "Harp Queen ~ 50 Jewel of Creation",
            "Demon Knight ~ 10 Random Mount Fragment",
        ],
    },
    {
        name: "Golden Invasion",
        times: [
            "00:30",
            "02:30",
            "04:30",
            "06:30",
            "08:30",
            "10:30",
            "12:30",
            "14:30",
            "16:30",
            "18:30",
            "20:30",
            "22:30",
        ],
        type: TEventType.CASUAL,
        map: "Everywhere",
        rewards: ["Box of Kundun +1", "Box of Kundun +2", "Box of Kundun +3", "Box of Kundun +4", "Box of Kundun +5"],
    },
    {
        name: "Evomon",
        times: [
            "00:10",
            "02:10",
            "04:10",
            "06:10",
            "08:10",
            "10:10",
            "12:10",
            "14:10",
            "16:10",
            "18:10",
            "20:10",
            "22:10",
        ],
        type: TEventType.CASUAL,
        map: "Tarkan",
        rewards: ["Jewels from Evomon Boxes"],
    },
    {
        name: "Army of Shadow",
        times: ["02:20", "05:20", "08:20", "11:20", "14:20", "17:20", "20:20", "23:20"],
        type: TEventType.CASUAL,
        map: "Karutan 2",
        rewards: ["Shadowforce Stone"],
    },
    {
        name: "Bali Invasion",
        times: ["02:45", "05:45", "08:45", "11:45", "14:45", "17:45", "20:45", "23:45"],
        type: TEventType.CASUAL,
        map: "Noria",
        rewards: ["Mount Fragments", "Jewel of Creation"],
    },
    {
        name: "Pouch Hunting",
        times: [
            "00:15",
            "01:45",
            "03:15",
            "04:45",
            "06:15",
            "07:45",
            "09:15",
            "10:45",
            "12:15",
            "13:45",
            "15:15",
            "16:45",
            "18:15",
            "19:45",
            "21:15",
            "22:45",
        ],
        type: TEventType.CASUAL,
        map: "Aida",
        rewards: [
            "Suspicious Scrap of Paper",
            "Sign of Dimension",
            "Jewel of Bless",
            "Jewel of Soul",
            "Jewel of Life",
            "Jewel of Creation",
        ],
    },
    {
        name: "Crywolf Fortress",
        times: ["09:15", "21:15"],
        type: TEventType.CASUAL,
        map: "Crywolf",
        rewards: ["10 Jewel (For altar elfs)", "Excellent Items", "3 380 Excellent Items with 2-4 options"],
    },
    {
        name: "Castle Deep",
        times: ["01:15", "07:15", "13:15", "19:15"],
        type: TEventType.CASUAL,
        map: "Valley of Loren",
        rewards: ["5 Excellent Items with 3-4 options"],
    },
    {
        name: "Chaos Castle",
        times: [
            "01:00",
            "03:00",
            "05:00",
            "07:00",
            "09:00",
            "11:00",
            "13:00",
            "15:00",
            "17:00",
            "19:00",
            "21:00",
            "23:00",
        ],
        type: TEventType.CASUAL,
        map: "Chaos Castle",
        rewards: ["Ancient Item", "20 Jewel of Bless", "20 Jewel of Soul", "20 Jewel of Life", "10 Jewel of Creation"],
    },
    {
        name: "Blood Castle",
        times: [
            "00:00",
            "02:00",
            "04:00",
            "06:00",
            "08:00",
            "10:00",
            "12:00",
            "14:00",
            "16:00",
            "18:00",
            "20:00",
            "22:00",
        ],
        type: TEventType.CASUAL,
        map: "Blood Castle, entry: Devias",
        rewards: [
            "Mount Fragments",
            "Pet Panda",
            "Panda Ring",
            "Steel Dinorant",
            "Obsidian Dinorant",
            "Unicorn Uniria",
            "10 Jewel of Creation",
            "20 Jewel of Bless",
            "20 Jewel of Soul",
            "20 Jewel of Life",
            "Talisman of Chaos Assembly",
            "Excellent Item",
        ],
    },
    {
        name: "Moss The Gambler",
        times: ["02:15", "05:15", "08:15", "11:15", "14:15", "17:15", "20:15", "23:15"],
        type: TEventType.IMPORTANT,
        map: "Elbeland",
        rewards: ["Ancient item for 20 Jewel of Creation"],
    },
    {
        name: "Devil Square",
        times: ["01:30", "03:30", "05:30", "07:30", "11:30", "13:30", "15:30", "17:30", "19:30", "21:30", "23:30"],
        type: TEventType.CASUAL,
        map: "Devil Square, entry: Noria",
        rewards: ["Chaos Card", "Divine Weapons"],
    },
    {
        name: "God of Darkness",
        times: ["06:35", "18:35"],
        type: TEventType.IMPORTANT,
        map: "Swamp of Darkness",
        rewards: ["Excellent Mastery Equipment", "3 opened Golden Box"],
    },
    {
        name: "Nixie",
        times: ["01:20", "07:20", "13:20", "19:20"],
        type: TEventType.IMPORTANT,
        map: "Nixie's Lake",
        rewards: [
            "10 Jewel of Harmony (bundled)",
            "10 Jewel of Creation (bundled)",
            "Sealed Silver Box",
            "Silver Key",
            "Sealed Golden Box",
            "Golden Key",
        ],
    },
    {
        name: "Lord of Ferea",
        times: ["04:35", "12:35", "20:35"],
        type: TEventType.IMPORTANT,
        map: "Ferea",
        rewards: ["Sealed Silver Box", "Silver Key", "Sealed Golden Box", "Golden Key", "Talisman of Chaos Assembly"],
    },
    {
        name: "Medusa",
        times: [
            "00:20",
            "02:20",
            "04:20",
            "06:20",
            "08:20",
            "10:20",
            "12:20",
            "14:20",
            "16:20",
            "18:20",
            "20:20",
            "22:20",
        ],
        type: TEventType.IMPORTANT,
        map: "Peace Swamp",
        rewards: [
            "Jewel of Creation",
            "Silver Key",
            "Sealed Silver Box",
            "Golden Key",
            "Sealed Golden Box",
            "Steel of Heaven",
        ],
    },
];
